# Generated by Django 3.2 on 2022-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='video link')),
                ('query_date', models.DateTimeField(auto_now_add=True, verbose_name='query date')),
            ],
        ),
    ]
